### ISSUE TITLE
Layer Fails to load

### ISSUE THREAD

**Issue by mclark4386** [averrin/dart-layer#1]
Not entirely sure how to debug this as this is a first for me, but I followed the instructions to install this layer and it is failing to load:
<img width="735" alt="screen shot 2018-05-10 at 4 06 16 am" src="https://user-images.githubusercontent.com/484943/39861865-963ae482-5407-11e8-8204-f2d104c473d4.png">

Happy to help how ever I can in fixing this as I love spacemacs and dart^^

**Comment by averrin** [comment]
Now i use doom-emacs and this layer is depricated. You can use lsp-mode for analyzer functions and my dart-mode branch https://github.com/averrin/dart-mode/tree/lite for syntax highlight.

**Comment by mclark4386** [comment]
thanks for the update!
